controller_list:
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
  - name: fake_hand_controller
    joints:
      - joint4
      - joint5
      - joint6
      - joint7
      - joint8
      - joint9
initial:  # Define initial robot poses.
  - group: arm
    pose: arm_home